version: "3.9"

services:
  inference:
    build: ./inference
    container_name: inference_api
    ports:
      - "8000:8000"

  ui:
    build: ./ui
    container_name: ui_gradio
    ports:
      - "7860:7860"
    depends_on:
      - inference

